/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.AdmintrativeRole;

import Business.SupplierDirectory;
import javax.swing.JPanel;
import Business.Product;
import Business.Supplier;
import java.awt.CardLayout;
import javax.swing.table.DefaultTableModel;
import Business.ProductCatalog;
import java.awt.Component;

/**
 *
 * @author prane
 */
public class ViewSupplier extends javax.swing.JPanel {

    /**
     * Creates new form ViewSupplier
     */
    private JPanel userProcessContainer;
    private Supplier supplier;
    public ViewSupplier(JPanel upc, Supplier s) {
        initComponents();
        userProcessContainer=upc;
        supplier=s;
        supplierName.setText(supplier.getSupplierName());
        refreshTable();
    }
    
    private void refreshTable()
    {
        int rowCount=productCatalog.getRowCount();
        DefaultTableModel model = (DefaultTableModel) productCatalog.getModel();
        
        for(int i=rowCount-1;i>=0;i--)
        {
            model.removeRow(i);
        }
        
        for(Product p : supplier.getProductCatalog().getProductCatalog())
        {
            Object row[]=new Object[3];
            row[0]=p;
            row[1]=p.getModelNumber();
            row[2]=p.getPrice();
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        supplierName = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        productCatalog = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        supplierName.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        supplierName.setText("Supplier Name");
        add(supplierName, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 30, -1, -1));

        productCatalog.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Product Name", "Mobile Number", "Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(productCatalog);
        if (productCatalog.getColumnModel().getColumnCount() > 0) {
            productCatalog.getColumnModel().getColumn(0).setResizable(false);
            productCatalog.getColumnModel().getColumn(1).setResizable(false);
            productCatalog.getColumnModel().getColumn(2).setResizable(false);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 90, 375, 275));

        jButton1.setText("<<BACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 410, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        userProcessContainer.remove(this);
       Component[] componentArray=userProcessContainer.getComponents();
       Component component= componentArray[componentArray.length-1];
       ManageSuppliers manageSuppliers=(ManageSuppliers) component;
       manageSuppliers.populateTable(); 
       CardLayout layout=(CardLayout)userProcessContainer.getLayout();
       layout.previous(userProcessContainer); 
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable productCatalog;
    private javax.swing.JLabel supplierName;
    // End of variables declaration//GEN-END:variables
}
