/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.VitalSignHistory;
import Business.VitalSigns;
import Business.DataValidation;
import javax.swing.JOptionPane;

/**
 *
 * @author prane
 */
public class CreateVitalJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateVitalJPanel
     */
    private VitalSignHistory vsh;

    CreateVitalJPanel(VitalSignHistory vsh) {
        initComponents();
        this.vsh = vsh;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tempLbl = new javax.swing.JLabel();
        pulseLbl = new javax.swing.JLabel();
        bloodpressureLbl = new javax.swing.JLabel();
        dateLbl = new javax.swing.JLabel();
        temperatureTextField = new javax.swing.JTextField();
        bloodpressureTextField = new javax.swing.JTextField();
        pulseTextField = new javax.swing.JTextField();
        dateTextField = new javax.swing.JTextField();
        createheaderLbl = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tempLbl.setText("Temparature");
        add(tempLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 105, -1, -1));

        pulseLbl.setText("Pulse");
        add(pulseLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 175, -1, -1));

        bloodpressureLbl.setText("Blood Pressure");
        add(bloodpressureLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 140, -1, -1));

        dateLbl.setText("Date");
        add(dateLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 210, -1, -1));
        add(temperatureTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(237, 105, 171, -1));
        add(bloodpressureTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(237, 140, 171, -1));
        add(pulseTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(237, 175, 171, -1));
        add(dateTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(237, 210, 171, -1));

        createheaderLbl.setFont(new java.awt.Font("Calibri Light", 1, 24)); // NOI18N
        createheaderLbl.setText("Record Vital Signs");
        add(createheaderLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 210, 38));

        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 270, 160, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        boolean checktemp = false;
        boolean checkbp = false;
        boolean checkpulse = false;

        DataValidation dvobj = new DataValidation();
        checkpulse = dvobj.checkNumeric(pulseTextField.getText());
        checkbp = dvobj.checkNumeric(bloodpressureTextField.getText());
        checktemp = dvobj.checkNumeric(temperatureTextField.getText());

        if (checkpulse == true & checkbp == true & checktemp == true) {
            double temperature = Double.parseDouble(temperatureTextField.getText());
            double bp = Double.parseDouble(bloodpressureTextField.getText());
            int pulse = Integer.parseInt(pulseTextField.getText());
            String date = dateTextField.getText();
            VitalSigns v = vsh.addVitals();
            v.setBloodPressure(bp);
            v.setTemperature(temperature);
            v.setDate(date);
            v.setPulse(pulse);
            JOptionPane.showMessageDialog(null, "Vitals recorded successfully");
            bloodpressureTextField.setText("");
            temperatureTextField.setText("");
            pulseTextField.setText("");
            dateTextField.setText("");
        } else {
            JOptionPane.showMessageDialog(null, "Please check your input. There is something wrong.");
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bloodpressureLbl;
    private javax.swing.JTextField bloodpressureTextField;
    private javax.swing.JLabel createheaderLbl;
    private javax.swing.JLabel dateLbl;
    private javax.swing.JTextField dateTextField;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel pulseLbl;
    private javax.swing.JTextField pulseTextField;
    private javax.swing.JLabel tempLbl;
    private javax.swing.JTextField temperatureTextField;
    // End of variables declaration//GEN-END:variables
}
