/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

//import statements
import Business.VitalSignHistory;
import Business.VitalSigns;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author prane
 */
public class ViewVitalJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewVitalJPanel
     */
    private VitalSignHistory vsh;

    public ViewVitalJPanel(VitalSignHistory vsh) {
        initComponents();
        this.vsh = vsh;
        populateTable();
    }

    public void populateTable() {
        DefaultTableModel dtm = (DefaultTableModel) vitalJTable.getModel();
        dtm.setRowCount(0);

        for (VitalSigns vs : vsh.getVitalSignHistory()) {
            Object row[] = new Object[2];
            row[0] = vs;
            row[1] = vs.getBloodPressure();
            dtm.addRow(row);

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        viewheaderLbl = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        vitalJTable = new javax.swing.JTable();
        tempLbl = new javax.swing.JLabel();
        bloodpressureLbl = new javax.swing.JLabel();
        pulseLbl = new javax.swing.JLabel();
        dateLbl = new javax.swing.JLabel();
        dateTextField = new javax.swing.JTextField();
        pulseTextField = new javax.swing.JTextField();
        bloodpressureTextField = new javax.swing.JTextField();
        temperatureTextField = new javax.swing.JTextField();
        viewdetailBtn = new javax.swing.JButton();
        deleteentryBtn = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        viewheaderLbl.setFont(new java.awt.Font("Calibri Light", 1, 24)); // NOI18N
        viewheaderLbl.setText("View Vitals");
        add(viewheaderLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, 139, 44));

        vitalJTable.setFont(new java.awt.Font("Calibri", 0, 13)); // NOI18N
        vitalJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date", "Blood Pressure"
            }
        ));
        jScrollPane1.setViewportView(vitalJTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 470, 146));

        tempLbl.setText("Temparature");
        add(tempLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, 90, -1));

        bloodpressureLbl.setText("Blood Pressure");
        add(bloodpressureLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 305, 100, -1));

        pulseLbl.setText("Pulse");
        add(pulseLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 340, 30, -1));

        dateLbl.setFont(new java.awt.Font("Calibri", 0, 13)); // NOI18N
        dateLbl.setText("Date");
        add(dateLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 375, 30, -1));

        dateTextField.setFont(new java.awt.Font("Calibri", 0, 13)); // NOI18N
        dateTextField.setEnabled(false);
        add(dateTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 375, 171, -1));

        pulseTextField.setFont(new java.awt.Font("Calibri", 0, 13)); // NOI18N
        pulseTextField.setEnabled(false);
        add(pulseTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 340, 171, -1));

        bloodpressureTextField.setFont(new java.awt.Font("Calibri", 0, 13)); // NOI18N
        bloodpressureTextField.setEnabled(false);
        add(bloodpressureTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 305, 171, -1));

        temperatureTextField.setFont(new java.awt.Font("Calibri", 0, 13)); // NOI18N
        temperatureTextField.setEnabled(false);
        add(temperatureTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 270, 171, -1));

        viewdetailBtn.setFont(new java.awt.Font("Calibri", 0, 13)); // NOI18N
        viewdetailBtn.setText("View Details");
        viewdetailBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewdetailBtnActionPerformed(evt);
            }
        });
        add(viewdetailBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 220, -1, -1));

        deleteentryBtn.setFont(new java.awt.Font("Calibri", 0, 13)); // NOI18N
        deleteentryBtn.setText("Delete Entry");
        deleteentryBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteentryBtnActionPerformed(evt);
            }
        });
        add(deleteentryBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 220, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void viewdetailBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewdetailBtnActionPerformed
        // TODO add your handling code here:
        int selectedrow = vitalJTable.getSelectedRow();

        if (selectedrow >= 0) {
            VitalSigns vs = (VitalSigns) vitalJTable.getValueAt(selectedrow, 0);
            bloodpressureTextField.setText(String.valueOf(vs.getBloodPressure()));
            temperatureTextField.setText(String.valueOf(vs.getTemperature()));
            pulseTextField.setText(String.valueOf(vs.getPulse()));
            dateTextField.setText(String.valueOf(vs.getDate()));
        } else {
            JOptionPane.showMessageDialog(null, "Please select any row");
        }
    }//GEN-LAST:event_viewdetailBtnActionPerformed

    private void deleteentryBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteentryBtnActionPerformed
        // TODO add your handling code here:
        int selectedrow = vitalJTable.getSelectedRow();

        if (selectedrow >= 0) {
            int response = JOptionPane.showConfirmDialog(null, "Are you sure if these values are to be deleted?", null, JOptionPane.YES_NO_OPTION);

            if (response == JOptionPane.YES_OPTION) {
                VitalSigns vs = (VitalSigns) vitalJTable.getValueAt(selectedrow, 0);
                vsh.deleteVitals(vs);
                JOptionPane.showMessageDialog(null, "Vitals are deleted");
                populateTable();
                bloodpressureTextField.setText("");
                temperatureTextField.setText("");
                pulseTextField.setText("");
                dateTextField.setText("");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Please select any row");
        }

    }//GEN-LAST:event_deleteentryBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bloodpressureLbl;
    private javax.swing.JTextField bloodpressureTextField;
    private javax.swing.JLabel dateLbl;
    private javax.swing.JTextField dateTextField;
    private javax.swing.JButton deleteentryBtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel pulseLbl;
    private javax.swing.JTextField pulseTextField;
    private javax.swing.JLabel tempLbl;
    private javax.swing.JTextField temperatureTextField;
    private javax.swing.JButton viewdetailBtn;
    private javax.swing.JLabel viewheaderLbl;
    private javax.swing.JTable vitalJTable;
    // End of variables declaration//GEN-END:variables
}
