/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ResumeInterface;
import Career.DataValidation;
import Career.Resume;
import Career.ResumeHistory;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author prane
 */
public class ViewResumeJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewResumeJPanel
     */
    private ResumeHistory resumehistoryobj;
    public ViewResumeJPanel(ResumeHistory resumehistoryobj) {
        initComponents();
        this.resumehistoryobj=resumehistoryobj;
       
        //displayProfile(resumeobj);
        populateTable();
    }
    
    private void populateTable()
    {
        DefaultTableModel dtm = (DefaultTableModel) resumeJTable.getModel();
        dtm.setRowCount(0);

        for (Resume resumeobj : resumehistoryobj.getResumeHistory()) 
        {
            Object row[] = new Object[2];
            row[0] = resumeobj;
            row[1] = resumeobj.getFirstname();
            dtm.addRow(row);
            
        }
    }
private void displayProfile(Resume resumeobj)
    {
        //Fetching data from objects and storing in the variables.
        String firstName = resumeobj.getFirstname();
        String lastName = resumeobj.getLastname();
        String address = resumeobj.getAddress();
        String contact = resumeobj.getPhonenumber();
        String linkedinprof = resumeobj.getLinkedinprof();
        String careerobjective = resumeobj.getCareerobjective();
        String gradcollegename = resumeobj.getEdugradname();
        String gradcollegedate = resumeobj.getEdugraddate();
        String undergradcollegedate = resumeobj.getEduundergraddate();
        String undergradcollegename = resumeobj.getEduundergradname();
        String skill=resumeobj.getSkill();
        String certification=resumeobj.getCertification();
        String schooldate = resumeobj.getEduhighschooldate();
        String schoolname = resumeobj.getEduhighschoolname();
        String programmingskills=resumeobj.getProgrammingskill();
        String englishproficiency=resumeobj.getEnglishproficiency();
        String gender=resumeobj.getGender();
        String emailid=resumeobj.getEmailid();
        String locationpref=resumeobj.getLocationpreference();
        
        //displaying in the labels of the view page using the variables.
        ImageIcon image= resumeobj.getImage();
        emailidLbl.setText(emailid);
        imageLbl.setIcon(image);
        englishprofLbl.setText(englishproficiency);
        genderLbl.setText(gender);
        certificationsLbl.setText(certification);
        programmingskillsLbl.setText(programmingskills);
        nameLbl.setText(firstName+" "+lastName);
        addressLbl.setText(address);
        linkedinLbl.setText(linkedinprof);
        careerobjectiveLbl.setText(careerobjective);
        gradnameLbl.setText(gradcollegename);
        graddateLbl.setText(gradcollegedate);
        undergraddateLbl.setText(undergradcollegedate);
        undergradnameLbl.setText(undergradcollegename);
        certificationsLbl.setText(certification);
        schooldateLbl.setText(schooldate);
        schoolnameLbl.setText(schoolname);
        phoneLbl.setText(contact);
        locationprefLbl.setText(locationpref);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nameLbl = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        addressLbl = new java.awt.Label();
        phoneLbl = new java.awt.Label();
        linkedinLbl = new java.awt.Label();
        label4 = new java.awt.Label();
        gradnameLbl = new java.awt.Label();
        undergraddateLbl = new java.awt.Label();
        schoolnameLbl = new java.awt.Label();
        graddateLbl = new java.awt.Label();
        label9 = new java.awt.Label();
        certificationsLbl = new java.awt.Label();
        jLabel3 = new javax.swing.JLabel();
        careerobjectiveLbl = new javax.swing.JLabel();
        label11 = new java.awt.Label();
        programmingskillsLbl = new java.awt.Label();
        undergradnameLbl = new java.awt.Label();
        schooldateLbl = new java.awt.Label();
        jLabel1 = new javax.swing.JLabel();
        imageLbl = new javax.swing.JLabel();
        viewdetailBtn = new javax.swing.JButton();
        deleteentryBtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        genderLbl = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        englishprofLbl = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        resumeJTable = new javax.swing.JTable();
        emailidLbl = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        locationprefLbl = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nameLbl.setFont(new java.awt.Font("Calibri Light", 1, 24)); // NOI18N
        nameLbl.setText("Name of the Candidate");
        add(nameLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 272, 32));

        jLabel2.setText("---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 1540, -1));

        addressLbl.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        addressLbl.setText("Address of the candidate");
        add(addressLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 390, -1));
        addressLbl.getAccessibleContext().setAccessibleName("addressLbl");

        phoneLbl.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        phoneLbl.setText("Phone contact");
        add(phoneLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 116, -1));

        linkedinLbl.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        linkedinLbl.setText("LinkedIn Profile");
        add(linkedinLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 365, -1));

        label4.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        label4.setText("Education");
        add(label4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, -1, -1));

        gradnameLbl.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        gradnameLbl.setText("Grad College");
        add(gradnameLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, -1, -1));

        undergraddateLbl.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        undergraddateLbl.setText("Date");
        add(undergraddateLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 490, 65, -1));

        schoolnameLbl.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        schoolnameLbl.setText("High School");
        add(schoolnameLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 520, -1, -1));

        graddateLbl.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        graddateLbl.setText("Date");
        add(graddateLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 460, 64, -1));

        label9.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        label9.setText("Certifications");
        add(label9, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 590, -1, 45));

        certificationsLbl.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        certificationsLbl.setText("List of Certifications");
        add(certificationsLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 630, 268, 45));
        certificationsLbl.getAccessibleContext().setAccessibleName("Certifications");

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel3.setText("Career Objective");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, -1, -1));

        careerobjectiveLbl.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        careerobjectiveLbl.setText("Career Objective Statement");
        add(careerobjectiveLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 478, 45));

        label11.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        label11.setText("Programming Skills");
        add(label11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 590, 130, 39));

        programmingskillsLbl.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        programmingskillsLbl.setText("List of Skills");
        add(programmingskillsLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 630, 176, 35));

        undergradnameLbl.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        undergradnameLbl.setText("Undergrad College");
        add(undergradnameLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 490, -1, -1));

        schooldateLbl.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        schooldateLbl.setText("Date");
        add(schooldateLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 520, 65, -1));

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel1.setText("Photograph");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 240, -1, -1));

        imageLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/default_profile_picture.png"))); // NOI18N
        imageLbl.setDoubleBuffered(true);
        add(imageLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 250, 144, 128));

        viewdetailBtn.setText("View Details");
        viewdetailBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewdetailBtnActionPerformed(evt);
            }
        });
        add(viewdetailBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 30, -1, -1));

        deleteentryBtn.setText("Delete Entry");
        deleteentryBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteentryBtnActionPerformed(evt);
            }
        });
        add(deleteentryBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 80, -1, -1));

        jLabel5.setFont(new java.awt.Font("Calibri", 0, 13)); // NOI18N
        jLabel5.setText("Gender :");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 390, -1, -1));

        genderLbl.setFont(new java.awt.Font("Calibri", 0, 13)); // NOI18N
        genderLbl.setText("Gender ");
        add(genderLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 390, -1, -1));
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(528, 497, -1, -1));

        englishprofLbl.setFont(new java.awt.Font("Calibri", 0, 13)); // NOI18N
        englishprofLbl.setText("Level");
        add(englishprofLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 420, 45, -1));

        jLabel8.setFont(new java.awt.Font("Calibri", 0, 13)); // NOI18N
        jLabel8.setText("English Proficiency :");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 420, -1, -1));

        resumeJTable.setFont(new java.awt.Font("Calibri", 0, 13)); // NOI18N
        resumeJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Last Name", "First Name"
            }
        ));
        jScrollPane1.setViewportView(resumeJTable);

        jScrollPane2.setViewportView(jScrollPane1);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 536, 135));

        emailidLbl.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        emailidLbl.setText("Email ID");
        add(emailidLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, -1, -1));

        jLabel4.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel4.setText("Affiliation");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 550, -1, -1));

        jLabel7.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel7.setText("Affiliation value");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 550, -1, -1));

        jLabel9.setText("Location Preference:");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 450, -1, -1));

        locationprefLbl.setText("Location");
        add(locationprefLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 450, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void deleteentryBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteentryBtnActionPerformed
        // TODO add your handling code here:
        
        int selectedrow = resumeJTable.getSelectedRow();

        if (selectedrow >= 0) {
            int response = JOptionPane.showConfirmDialog(null, "Are you sure if these values are to be deleted?", null, JOptionPane.YES_NO_OPTION);

            if (response == JOptionPane.YES_OPTION) 
            {
                Resume res = (Resume) resumeJTable.getValueAt(selectedrow, 0);
                resumehistoryobj.deleteResume(res);
                JOptionPane.showMessageDialog(null, "Resume deleted");
                populateTable();
            }
        } else {
            JOptionPane.showMessageDialog(null, "Please select any row");
        }
        
        
    }//GEN-LAST:event_deleteentryBtnActionPerformed

    private void viewdetailBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewdetailBtnActionPerformed
        // TODO add your handling code here:
        int selectedrow = resumeJTable.getSelectedRow();

        if (selectedrow >= 0) {
            Resume res = (Resume) resumeJTable.getValueAt(selectedrow, 0);
            displayProfile(res);
        } else {
            JOptionPane.showMessageDialog(null, "Please select any row");
        }
    }//GEN-LAST:event_viewdetailBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Label addressLbl;
    private javax.swing.JLabel careerobjectiveLbl;
    private java.awt.Label certificationsLbl;
    private javax.swing.JButton deleteentryBtn;
    private javax.swing.JLabel emailidLbl;
    private javax.swing.JLabel englishprofLbl;
    private javax.swing.JLabel genderLbl;
    private java.awt.Label graddateLbl;
    private java.awt.Label gradnameLbl;
    private javax.swing.JLabel imageLbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private java.awt.Label label11;
    private java.awt.Label label4;
    private java.awt.Label label9;
    private java.awt.Label linkedinLbl;
    private javax.swing.JLabel locationprefLbl;
    private javax.swing.JLabel nameLbl;
    private java.awt.Label phoneLbl;
    private java.awt.Label programmingskillsLbl;
    private javax.swing.JTable resumeJTable;
    private java.awt.Label schooldateLbl;
    private java.awt.Label schoolnameLbl;
    private java.awt.Label undergraddateLbl;
    private java.awt.Label undergradnameLbl;
    private javax.swing.JButton viewdetailBtn;
    // End of variables declaration//GEN-END:variables
}
