/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.Account;
import Business.AccountDirectory;
import Business.DataValidation;
import static Business.DataValidation.alphabetCheck;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author prane
 */
public class CreateAccountJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private AccountDirectory accountDirectory;
    /**
     * Creates new form CreateAccountJPanel
     */
    public CreateAccountJPanel(JPanel userProcessContainer, AccountDirectory accountDirectory)
    {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.accountDirectory=accountDirectory;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblHeader = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtRoutingNumber = new javax.swing.JTextField();
        txtAccountNumber = new javax.swing.JTextField();
        txtBankName = new javax.swing.JTextField();
        txtBalance = new javax.swing.JTextField();
        btnCreate = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblHeader.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        lblHeader.setText("Create Account");
        add(lblHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 35, 150, -1));

        jLabel2.setText("Routing Number");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 94, -1, -1));

        jLabel3.setText("Account Number");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 123, -1, -1));

        jLabel4.setText("Bank Name");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, -1, -1));

        jLabel5.setText("Balance");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, -1, -1));
        add(txtRoutingNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 91, 118, -1));
        add(txtAccountNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 120, 118, -1));
        add(txtBankName, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 154, 118, -1));
        add(txtBalance, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 191, 118, 30));

        btnCreate.setText("Create Account");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });
        add(btnCreate, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, -1, -1));

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 75, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
    
    try
    {
        String flag = "true";
        String routingNumber=txtRoutingNumber.getText();
        String accountNumber=txtAccountNumber.getText();
        String bankName=txtBankName.getText();
        int balance = Integer.parseInt(txtBalance.getText());
        
        DataValidation dv = new DataValidation();
        
        if(dv.checkNumeric(routingNumber) && dv.checkNumeric(accountNumber) && dv.checkNumeric(txtBalance.getText())){}
        else
            flag = "false";
        
        if(alphabetCheck(bankName)){}
        else
            flag = "false";
        
        if(flag=="false")
            throw new Exception();
        
        Account account =accountDirectory.addAccount();
        account.setRoutingnumber(routingNumber);
        account.setBalance(balance);
        account.setAccountnumber(accountNumber);
        account.setBankname(bankName);
        
        JOptionPane.showMessageDialog(null, "Account successfully created");
    }
    catch(Exception e)
    {
        JOptionPane.showMessageDialog(null, "Please check your input values");
    }
    }//GEN-LAST:event_btnCreateActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout =(CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
        
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCreate;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblHeader;
    private javax.swing.JTextField txtAccountNumber;
    private javax.swing.JTextField txtBalance;
    private javax.swing.JTextField txtBankName;
    private javax.swing.JTextField txtRoutingNumber;
    // End of variables declaration//GEN-END:variables
}
