/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface;

import business.Business;
import business.Person;
import business.UserAccount;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Ujjval
 */
public class AddUserAccountJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AddUserAccountJPanel
     */
    private JPanel userProcessContainer;
    private Business business;

    public AddUserAccountJPanel(JPanel userProcessContainer, Business business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.business = business;
        populatePerson();
        populateRoles();
    }

    public void populatePerson() {
        personJComboBox.removeAll();
        for (Person p : business.getEmployeeDirectory().getEmployeeList()) {
            personJComboBox.addItem(p);
        }
    }

    public void populateRoles() {
        roleJComboBox.removeAll();
        roleJComboBox.addItem(UserAccount.EMPLOYEE_ROLE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblHeader = new javax.swing.JLabel();
        lblUserName = new javax.swing.JLabel();
        lblPwd = new javax.swing.JLabel();
        lblIsActive = new javax.swing.JLabel();
        lblPerson = new javax.swing.JLabel();
        lblRole = new javax.swing.JLabel();
        roleJComboBox = new javax.swing.JComboBox<>();
        personJComboBox = new javax.swing.JComboBox();
        inactiveJRadioButton = new javax.swing.JRadioButton();
        activeJRadioButton = new javax.swing.JRadioButton();
        txtPwdField = new javax.swing.JTextField();
        txtUserName = new javax.swing.JTextField();
        btnCreateUserAccount = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        lblHeader.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblHeader.setText("Add New User Account");

        lblUserName.setText("User Name:");

        lblPwd.setText("Password:");

        lblIsActive.setText("IsActive:");

        lblPerson.setText("Person:");

        lblRole.setText("Role:");

        inactiveJRadioButton.setText("No");
        inactiveJRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inactiveJRadioButtonActionPerformed(evt);
            }
        });

        activeJRadioButton.setSelected(true);
        activeJRadioButton.setText("Yes");
        activeJRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                activeJRadioButtonActionPerformed(evt);
            }
        });

        btnCreateUserAccount.setText("Create UserAccount");
        btnCreateUserAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateUserAccountActionPerformed(evt);
            }
        });

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(lblHeader))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblUserName)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblPwd)
                                    .addComponent(lblIsActive)
                                    .addComponent(lblPerson)
                                    .addComponent(lblRole, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnBack))
                                .addGap(38, 38, 38)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(activeJRadioButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(inactiveJRadioButton))
                                    .addComponent(txtPwdField)
                                    .addComponent(txtUserName)
                                    .addComponent(personJComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(roleJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnCreateUserAccount))))))
                .addContainerGap(229, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblHeader)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUserName)
                    .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPwd)
                    .addComponent(txtPwdField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIsActive)
                    .addComponent(activeJRadioButton)
                    .addComponent(inactiveJRadioButton))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPerson)
                    .addComponent(personJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRole)
                    .addComponent(roleJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack)
                    .addComponent(btnCreateUserAccount))
                .addContainerGap(42, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void inactiveJRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inactiveJRadioButtonActionPerformed
        // TODO add your handling code here:
        if (inactiveJRadioButton.isSelected()) {
            activeJRadioButton.setSelected(false);
        }
    }//GEN-LAST:event_inactiveJRadioButtonActionPerformed

    private void activeJRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_activeJRadioButtonActionPerformed
        // TODO add your handling code here:
        if (activeJRadioButton.isSelected()) {
            inactiveJRadioButton.setSelected(false);
        }
    }//GEN-LAST:event_activeJRadioButtonActionPerformed

    private void btnCreateUserAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateUserAccountActionPerformed
        // TODO add your handling code here:

        String userName = txtUserName.getText().trim();
        String password = txtPwdField.getText().trim();

        if (userName.equals("") || password.equals("")) {
            JOptionPane.showMessageDialog(this, "Please enter all the fields", "error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        UserAccount ua = business.getUserAccountDirectory().addUser();
        ua.setUserName(userName);
        ua.setPassword(password);
        ua.setPerson((Person) personJComboBox.getSelectedItem());
        ua.setRole(String.valueOf(roleJComboBox.getSelectedItem()));

        if (activeJRadioButton.isSelected()) {
            ua.setIsActive(true);
        } else {
            ua.setIsActive(false);
        }
        JOptionPane.showMessageDialog(this, "User Account Created Successfully!!", "Info", JOptionPane.INFORMATION_MESSAGE);

        txtUserName.setText("");
        txtPwdField.setText("");
    }//GEN-LAST:event_btnCreateUserAccountActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] array = userProcessContainer.getComponents();
        Component component = array[array.length - 1];
        ManageUserAccountsJPanel muajp = (ManageUserAccountsJPanel) component;
        muajp.refreshTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton activeJRadioButton;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCreateUserAccount;
    private javax.swing.JRadioButton inactiveJRadioButton;
    private javax.swing.JLabel lblHeader;
    private javax.swing.JLabel lblIsActive;
    private javax.swing.JLabel lblPerson;
    private javax.swing.JLabel lblPwd;
    private javax.swing.JLabel lblRole;
    private javax.swing.JLabel lblUserName;
    private javax.swing.JComboBox personJComboBox;
    private javax.swing.JComboBox<String> roleJComboBox;
    private javax.swing.JTextField txtPwdField;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
}
