/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;

import Business.Product;
import Business.ComputerCollection;
import Business.HardwareCollection;
import Business.PrinterCollection;
import Business.SoftwareCollection;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author prane
 */
public class DeleteProductJPanel extends javax.swing.JPanel {

    /**
     * Creates new form DeleteProductJPanel
     */
    private JPanel userProcessContainer;
    private ComputerCollection computerCollection;
    private PrinterCollection printerCollection;
    private SoftwareCollection softwareCollection;
    private HardwareCollection hardwareCollection;
    public DeleteProductJPanel(JPanel userProcessContainer, ComputerCollection computerCollection, PrinterCollection printerCollection, SoftwareCollection softwareCollection, HardwareCollection hardwareCollection) {
        initComponents();
         this.userProcessContainer=userProcessContainer;
         this.computerCollection=computerCollection;
         this.printerCollection=printerCollection;
         this.softwareCollection=softwareCollection;
         this.hardwareCollection=hardwareCollection;
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel10 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        IDjTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        namejTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        modeljTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        deleteButton = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel10.setText("Please provide any of the below detail about the product");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 110, -1, -1));

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel3.setText("Specify Criteria");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, 130, 30));

        IDjTextField.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        add(IDjTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 190, 100, -1));

        jLabel4.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel4.setText("ID");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 160, -1, -1));

        jLabel11.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel11.setText("OR");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 160, -1, -1));

        jLabel6.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel6.setText("Name");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 160, -1, -1));

        namejTextField.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        add(namejTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 190, 100, -1));

        jLabel5.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel5.setText("OR");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 160, -1, -1));

        modeljTextField.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        add(modeljTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 190, 100, -1));

        jLabel7.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel7.setText("Model");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 160, -1, -1));

        deleteButton.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        deleteButton.setText("Delete Product");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });
        add(deleteButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 280, 170, 40));

        jLabel9.setFont(new java.awt.Font("Calibri Light", 1, 24)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Delete Product");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, 250, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
       
        Boolean result = false;
        if(computerCollection.deleteProduct(IDjTextField.getText(), namejTextField.getText(), modeljTextField.getText()))
        {
            result=true;
        }
        if(printerCollection.deleteProduct(IDjTextField.getText(), namejTextField.getText(), modeljTextField.getText()))
        {
            result=true;
        }
        if(softwareCollection.deleteProduct(IDjTextField.getText(), namejTextField.getText(), modeljTextField.getText()))
        {
            result=true;
        }
        if(hardwareCollection.deleteProduct(IDjTextField.getText(), namejTextField.getText(), modeljTextField.getText()))
        {
            result=true;
        }
        
        if(result==false)
        {
            JOptionPane.showConfirmDialog(null, "The Product is not deleted.","Information",JOptionPane.DEFAULT_OPTION);
        }
        else
        {
            JOptionPane.showConfirmDialog(null, "The Product is deleted successfully.","Information",JOptionPane.DEFAULT_OPTION);

        }
    }//GEN-LAST:event_deleteButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField IDjTextField;
    private javax.swing.JButton deleteButton;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField modeljTextField;
    private javax.swing.JTextField namejTextField;
    // End of variables declaration//GEN-END:variables
}
