/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;

import Business.DataValidation;
import Business.HardwareCollection;
import Business.Product;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author prane
 */
public class SearchHardwareJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SearchHardwareJPanel
     */
    private JPanel userProcessContainer;
    private HardwareCollection hardwareCollection;
    public SearchHardwareJPanel(JPanel userProcessContainer, HardwareCollection hardwareCollection) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
         this.hardwareCollection=hardwareCollection;
         populateTable();
    }

    private void populateTable()
    {
        DefaultTableModel dtm = (DefaultTableModel) HardwaresjTable.getModel();
        dtm.setRowCount(0);

        for (Product catalogproductobj : hardwareCollection.getHardwareList())
        {
            Object row[] = new Object[4];
            row[0] = catalogproductobj;
            row[1] = catalogproductobj.getPid();
            row[2] = catalogproductobj.getPtype();
            row[3] = catalogproductobj.getPmodel();
            dtm.addRow(row);           
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        HardwaresjTable = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        searchButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        IDjTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        modeljTextField = new javax.swing.JTextField();
        namejTextField = new javax.swing.JTextField();
        viewdetailsjButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        HardwaresjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Product Name", "Product ID", "Product Type", "Product Model"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(HardwaresjTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 760, 180));

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel3.setText("Criteria");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 360, 70, 30));

        searchButton.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        searchButton.setText("Search Product");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });
        add(searchButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 360, 150, -1));

        jLabel5.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel5.setText("OR");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 370, -1, -1));

        IDjTextField.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        add(IDjTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 400, 100, -1));

        jLabel4.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel4.setText("ID");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 370, -1, -1));

        jLabel6.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel6.setText("Name");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 370, -1, -1));

        jLabel7.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel7.setText("Model");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 370, -1, -1));

        modeljTextField.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        add(modeljTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 400, 100, -1));

        namejTextField.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        add(namejTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 400, 100, -1));

        viewdetailsjButton.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        viewdetailsjButton.setText("Open Product");
        viewdetailsjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewdetailsjButtonActionPerformed(evt);
            }
        });
        add(viewdetailsjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 250, 150, -1));

        backButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        backButton.setText("<--Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 36, -1, -1));

        jLabel9.setFont(new java.awt.Font("Calibri Light", 1, 24)); // NOI18N
        jLabel9.setText("Find your Hardware");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, 250, -1));

        jLabel10.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel10.setText("Please provide any of the below detail about the computer");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 320, -1, -1));

        jLabel11.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel11.setText("OR");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 370, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        
         try
        {
            DataValidation dv =new DataValidation();
            String flag1="true";
            String flag2="true";
            String flag3="true";
            if(dv.alphaNumericCheck(IDjTextField.getText()))
            {
                //Do nothing
            }
            else
            {
                flag1="false";  
            }
            if(dv.alphabetCheck(namejTextField.getText()))
            {
                //Do nothing
            }
            else
            {
                flag2="false";  
            }
            if(dv.alphaNumericCheck(modeljTextField.getText()))
            {
                //Do nothing
            }
            else
            {
                flag3="false";  
            }
            
            if(flag1=="false" && flag2=="false" && flag3=="false")
            {
                JOptionPane.showConfirmDialog(null, "Please provide atleast one entry.","Information",JOptionPane.DEFAULT_OPTION);
                throw new Exception();
            }
        
        ArrayList<Product> compcolarr=new ArrayList<>();
        
        compcolarr = hardwareCollection.searchProduct(IDjTextField.getText(), namejTextField.getText(), modeljTextField.getText());
        if(compcolarr==null)
        {
            JOptionPane.showConfirmDialog(null, "Please provide atleast one entry or there is no product found.","Information",JOptionPane.DEFAULT_OPTION);
        }
        else
        {
            DefaultTableModel dtm = (DefaultTableModel) HardwaresjTable.getModel();
            dtm.setRowCount(0);
        for (Product catalogproductobj : compcolarr)
        {
            Object row[] = new Object[4];
            row[0] = catalogproductobj;
            row[1] = catalogproductobj.getPid();
            row[2] = catalogproductobj.getPname();
            row[3] = catalogproductobj.getPmodel();
            dtm.addRow(row);           
        }

        }
        }
        catch (Exception e)
        {
            
        }
          
    }//GEN-LAST:event_searchButtonActionPerformed

    private void viewdetailsjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewdetailsjButtonActionPerformed
        int selectedRow=HardwaresjTable.getSelectedRow();
        if(selectedRow<0)
        {
            JOptionPane.showConfirmDialog(null, "Please select a row from the table","Information", JOptionPane.OK_OPTION);
        }
        else
        {
            Product product =(Product) HardwaresjTable.getValueAt(selectedRow, 0);
            ViewProductPanel panel = new ViewProductPanel(userProcessContainer,product);
            userProcessContainer.add("ViewProductPanel",panel);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
        }
    }//GEN-LAST:event_viewdetailsjButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout =(CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable HardwaresjTable;
    private javax.swing.JTextField IDjTextField;
    private javax.swing.JButton backButton;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField modeljTextField;
    private javax.swing.JTextField namejTextField;
    private javax.swing.JButton searchButton;
    private javax.swing.JButton viewdetailsjButton;
    // End of variables declaration//GEN-END:variables
}
