/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;

/**
 *
 * @author prane
 */


import Business.ComputerCollection;
import Business.Product;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

public class VendorProductSearchJPanel extends javax.swing.JPanel {

    /**
     * Creates new form VendorProductSearchJPanel
     */
private JPanel userProcessContainer;
private ComputerCollection computerCollection;

    public VendorProductSearchJPanel(JPanel userProcessContainer, ComputerCollection computerCollection) {
        initComponents();
         this.userProcessContainer=userProcessContainer;
         this.computerCollection=computerCollection;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel10 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        IDjTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        namejTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        modeljTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        deleteButton = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel10.setText("Please provide any of the below detail about the product");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, -1, -1));

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel3.setText("Criteria");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, 70, 30));

        IDjTextField.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        add(IDjTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 220, 100, -1));

        jLabel4.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel4.setText("ID");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 180, -1, -1));

        jLabel11.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel11.setText("OR");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 180, -1, -1));

        jLabel6.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel6.setText("Name");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 180, -1, -1));

        namejTextField.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        add(namejTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 220, 100, -1));

        jLabel5.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel5.setText("OR");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 180, -1, -1));

        modeljTextField.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        add(modeljTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 220, 100, -1));

        jLabel7.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel7.setText("Model");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 180, -1, -1));

        deleteButton.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        deleteButton.setText("View and Update");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });
        add(deleteButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 300, 180, -1));

        jLabel9.setFont(new java.awt.Font("Calibri Light", 1, 24)); // NOI18N
        jLabel9.setText("Search Product");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, 250, -1));

        backButton.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        backButton.setText("<--Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 28, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        
        ArrayList<Product> compcolarr=new ArrayList<>();
        
        compcolarr = computerCollection.searchProduct(IDjTextField.getText(), namejTextField.getText(), modeljTextField.getText());
        if(compcolarr==null)
        {
             JOptionPane.showConfirmDialog(null, "Please provide atleast one entry or there is no product found.","Information",JOptionPane.DEFAULT_OPTION);
        }
        else
        {
            
            
            VendorViewUpdateProductJPanel panel = new VendorViewUpdateProductJPanel(userProcessContainer,compcolarr,computerCollection);
            userProcessContainer.add("ViewProductPanel",panel);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);

        }
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout =(CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField IDjTextField;
    private javax.swing.JButton backButton;
    private javax.swing.JButton deleteButton;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField modeljTextField;
    private javax.swing.JTextField namejTextField;
    // End of variables declaration//GEN-END:variables
}
