/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;

import Business.ComputerCollection;
import Business.HardwareCollection;
import Business.PrinterCollection;
import Business.SoftwareCollection;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author prane
 */
public class VendorWorkareaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form VendorWorkareaJPanel
     */
    private JPanel userProcessContainer;
    private ComputerCollection computerCollection;
    private PrinterCollection printerCollection;
    private SoftwareCollection softwareCollection;
    private HardwareCollection hardwareCollection;
    private String flag="";
    
    public VendorWorkareaJPanel(JPanel userProcessJpanel, ComputerCollection computerCollection, PrinterCollection printerCollection, SoftwareCollection softwareCollection, HardwareCollection hardwareCollection) {
        initComponents();
        this.userProcessContainer=userProcessJpanel;
        this.computerCollection=computerCollection;
        this.printerCollection=printerCollection;
        this.softwareCollection=softwareCollection;
        this.hardwareCollection=hardwareCollection;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addproductjButton = new javax.swing.JButton();
        deleteproductjButton = new javax.swing.JButton();
        updateproductjButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        addproductjButton.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        addproductjButton.setText("Add Product");
        addproductjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addproductjButtonActionPerformed(evt);
            }
        });
        add(addproductjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 150, 90));

        deleteproductjButton.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        deleteproductjButton.setText("Delete Product");
        deleteproductjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteproductjButtonActionPerformed(evt);
            }
        });
        add(deleteproductjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 120, 150, 90));

        updateproductjButton.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        updateproductjButton.setText("View or Update Product");
        updateproductjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateproductjButtonActionPerformed(evt);
            }
        });
        add(updateproductjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 300, 230, 90));

        jLabel1.setFont(new java.awt.Font("Calibri Light", 1, 24)); // NOI18N
        jLabel1.setText("What do you want to do today?");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, 360, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void addproductjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addproductjButtonActionPerformed
        
        AddProductJPanel panel = new AddProductJPanel(userProcessContainer,computerCollection, printerCollection, softwareCollection, hardwareCollection);
        userProcessContainer.add("AddProductJPanel", panel);
        CardLayout layout =  (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
    }//GEN-LAST:event_addproductjButtonActionPerformed

    private void deleteproductjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteproductjButtonActionPerformed
       
        DeleteProductJPanel panel = new DeleteProductJPanel(userProcessContainer,computerCollection, printerCollection, softwareCollection, hardwareCollection);
        userProcessContainer.add("DeleteProductJPanel", panel);
        CardLayout layout =  (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_deleteproductjButtonActionPerformed

    private void updateproductjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateproductjButtonActionPerformed
        VendorProductSearchJPanel panel = new VendorProductSearchJPanel(userProcessContainer,computerCollection);
        userProcessContainer.add("VendorProductSearchJPanel", panel);
        CardLayout layout =  (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);// TODO add your handling code here:
    }//GEN-LAST:event_updateproductjButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addproductjButton;
    private javax.swing.JButton deleteproductjButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton updateproductjButton;
    // End of variables declaration//GEN-END:variables
}
