/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;

import Business.ComputerCollection;
import Business.Product;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author prane
 */
public class VendorViewUpdateProductJPanel extends javax.swing.JPanel {

    /**
     * Creates new form VendorViewUpdateProductJPanel
     */
    private JPanel userProcessContainer;
    private ArrayList<Product> product;
    private ComputerCollection computerCollection;
    public VendorViewUpdateProductJPanel(JPanel userProcessContainer, ArrayList<Product> product, ComputerCollection computerCollection) {
        initComponents();
         this.product=product;
         this.userProcessContainer=userProcessContainer;
         this.computerCollection=computerCollection;
        populateProductDetails();   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        typejTextField = new javax.swing.JTextField();
        modeljTextField = new javax.swing.JTextField();
        modelidjTextField = new javax.swing.JTextField();
        basepricejTextField = new javax.swing.JTextField();
        vendornamejTextField = new javax.swing.JTextField();
        ceilingjTextField = new javax.swing.JTextField();
        floorpricejTextField = new javax.swing.JTextField();
        attachjButton = new javax.swing.JButton();
        SubmitjButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        descriptionjTextArea = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        benifitsjTextArea = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        featuresjTextArea = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        editjButton = new javax.swing.JButton();
        imageLbl = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel1.setText("Name ");
        jLabel1.setMaximumSize(new java.awt.Dimension(290, 290));
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, -1, -1));

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel2.setText("Type");
        jLabel2.setMaximumSize(new java.awt.Dimension(290, 290));
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, 40, -1));

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel3.setText("Model");
        jLabel3.setMaximumSize(new java.awt.Dimension(290, 290));
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, -1, -1));

        jLabel4.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel4.setText("Model ID");
        jLabel4.setMaximumSize(new java.awt.Dimension(290, 290));
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 170, 70, -1));

        jLabel5.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel5.setText("Description");
        jLabel5.setMaximumSize(new java.awt.Dimension(290, 290));
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 220, -1, -1));

        jLabel6.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel6.setText("Vendor Name");
        jLabel6.setMaximumSize(new java.awt.Dimension(290, 290));
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 290, -1, -1));

        jLabel7.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel7.setText("Base Price");
        jLabel7.setMaximumSize(new java.awt.Dimension(290, 290));
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 330, -1, -1));

        jLabel8.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel8.setText("Ceiling Price");
        jLabel8.setMaximumSize(new java.awt.Dimension(290, 290));
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 370, -1, -1));

        jLabel9.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel9.setText("Floor Price");
        jLabel9.setMaximumSize(new java.awt.Dimension(290, 290));
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 410, -1, -1));

        jLabel10.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel10.setText("Features");
        jLabel10.setMaximumSize(new java.awt.Dimension(290, 290));
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 470, -1, -1));

        jLabel11.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel11.setText("Display Picture");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 70, -1, -1));

        jLabel12.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel12.setText("Benifits");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 550, -1, -1));

        nameTextField.setEnabled(false);
        add(nameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 80, 200, -1));

        typejTextField.setEnabled(false);
        add(typejTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 110, 200, -1));

        modeljTextField.setEnabled(false);
        add(modeljTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 140, 200, -1));

        modelidjTextField.setEnabled(false);
        add(modelidjTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 170, 200, -1));

        basepricejTextField.setEnabled(false);
        add(basepricejTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 330, 200, -1));

        vendornamejTextField.setEnabled(false);
        add(vendornamejTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 290, 200, -1));

        ceilingjTextField.setEnabled(false);
        add(ceilingjTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 370, 200, -1));

        floorpricejTextField.setEnabled(false);
        add(floorpricejTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 410, 200, -1));

        attachjButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        attachjButton.setText("Attach");
        add(attachjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 250, 110, -1));

        SubmitjButton.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        SubmitjButton.setText("Submit");
        SubmitjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitjButtonActionPerformed(evt);
            }
        });
        add(SubmitjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 630, 110, 30));

        jScrollPane1.setEnabled(false);

        descriptionjTextArea.setColumns(20);
        descriptionjTextArea.setRows(5);
        descriptionjTextArea.setEnabled(false);
        jScrollPane1.setViewportView(descriptionjTextArea);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 200, 200, 80));

        benifitsjTextArea.setEditable(false);
        benifitsjTextArea.setColumns(20);
        benifitsjTextArea.setRows(5);
        benifitsjTextArea.setEnabled(false);
        jScrollPane2.setViewportView(benifitsjTextArea);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 530, 200, 80));

        featuresjTextArea.setColumns(20);
        featuresjTextArea.setLineWrap(true);
        featuresjTextArea.setRows(5);
        featuresjTextArea.setEnabled(false);
        jScrollPane3.setViewportView(featuresjTextArea);

        add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 450, 200, 70));

        jButton1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jButton1.setText("<--Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        jLabel13.setFont(new java.awt.Font("Calibri Light", 1, 24)); // NOI18N
        jLabel13.setText("Provide the details of the Product");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, 370, -1));

        editjButton.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        editjButton.setText("Edit");
        editjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editjButtonActionPerformed(evt);
            }
        });
        add(editjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 630, 110, 30));

        imageLbl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(imageLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(688, 96, 140, 140));
    }// </editor-fold>//GEN-END:initComponents

     private void populateProductDetails()
    {
        
        ImageIcon image= product.get(0).getImage();
        imageLbl.setIcon(image);
        nameTextField.setText(product.get(0).getPname());
        typejTextField.setText(product.get(0).getPtype());
        modelidjTextField.setText(product.get(0).getPmodelid());
        modeljTextField.setText(product.get(0).getPmodel());
        descriptionjTextArea.setText(product.get(0).getPdescription());
        vendornamejTextField.setText(product.get(0).getPvendorname());
        basepricejTextField.setText(product.get(0).getPbaseprice());
        ceilingjTextField.setText(product.get(0).getPceilingprice());
        floorpricejTextField.setText(product.get(0).getPfloorprice());
        featuresjTextArea.setText(product.get(0).getPfeatures());
        benifitsjTextArea.setText(product.get(0).getPbenefits());
    }
    
    private void SubmitjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitjButtonActionPerformed
 
        String pidtemp= product.get(0).getPid();
        
        
        Product productn =computerCollection.updateProduct(pidtemp);
        productn.setPid(pidtemp);
        productn.setPname(nameTextField.getText());
        productn.setPtype(typejTextField.getText());
        productn.setPmodel(modelidjTextField.getText());
        productn.setPmodelid(modelidjTextField.getText());
        productn.setPdescription(descriptionjTextArea.getText());
        productn.setPvendorname(vendornamejTextField.getText());
        productn.setPbaseprice(basepricejTextField.getText());
        productn.setPceilingprice(ceilingjTextField.getText());
        productn.setPfloorprice(floorpricejTextField.getText());
        productn.setPfeatures(featuresjTextArea.getText());
        productn.setPbenefits(benifitsjTextArea.getText());

        JOptionPane.showMessageDialog(null, "Product successfully updated");

    }//GEN-LAST:event_SubmitjButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout =(CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void editjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editjButtonActionPerformed
       
       
        nameTextField.setEnabled(true);
        typejTextField.setEnabled(true);
        modelidjTextField.setEnabled(true);
        modeljTextField.setEnabled(true);
        descriptionjTextArea.setEnabled(true);
        vendornamejTextField.setEnabled(true);
        basepricejTextField.setEnabled(true);
        ceilingjTextField.setEnabled(true);
        floorpricejTextField.setEnabled(true);
        featuresjTextArea.setEnabled(true);
        benifitsjTextArea.setEnabled(true);
    }//GEN-LAST:event_editjButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SubmitjButton;
    private javax.swing.JButton attachjButton;
    private javax.swing.JTextField basepricejTextField;
    private javax.swing.JTextArea benifitsjTextArea;
    private javax.swing.JTextField ceilingjTextField;
    private javax.swing.JTextArea descriptionjTextArea;
    private javax.swing.JButton editjButton;
    private javax.swing.JTextArea featuresjTextArea;
    private javax.swing.JTextField floorpricejTextField;
    private javax.swing.JLabel imageLbl;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField modelidjTextField;
    private javax.swing.JTextField modeljTextField;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JTextField typejTextField;
    private javax.swing.JTextField vendornamejTextField;
    // End of variables declaration//GEN-END:variables
}
