/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;
import Business.Product; //PR : Referring the class that we created.
/**
 *
 * @author Praneeth
 */
public class ViewJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewPanel
     */
    public ViewJPanel(Product product) {
        initComponents();
        displayProduct(product);
    }

    //function created to pass the object values to the view screen.
    private void displayProduct(Product product)
    {
        String productName = product.getName();
        nameTextField.setText(productName);
        
        String productPrice = product.getPrice();
        priceTextField.setText(productPrice);
        
        String productAvailability = product.getAvailNum();
        availnumberTextField.setText(productAvailability);
        
        String productDescription = product.getDescription();
        descriptionTextField.setText(productDescription);
         
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        viewheadLbl1 = new javax.swing.JLabel();
        nameLbl1 = new javax.swing.JLabel();
        priceLbl1 = new javax.swing.JLabel();
        availnumLbl1 = new javax.swing.JLabel();
        descLbl1 = new javax.swing.JLabel();
        descriptionTextField = new javax.swing.JTextField();
        availnumberTextField = new javax.swing.JTextField();
        priceTextField = new javax.swing.JTextField();
        nameTextField = new javax.swing.JTextField();

        setBackground(new java.awt.Color(153, 153, 153));
        setPreferredSize(new java.awt.Dimension(400, 302));

        viewheadLbl1.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        viewheadLbl1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        viewheadLbl1.setText("View Your Product");

        nameLbl1.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        nameLbl1.setText("Name");

        priceLbl1.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        priceLbl1.setText("Price");

        availnumLbl1.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        availnumLbl1.setText("Availability Number:");

        descLbl1.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        descLbl1.setText("Description :");

        descriptionTextField.setBackground(new java.awt.Color(204, 204, 204));
        descriptionTextField.setEnabled(false);

        availnumberTextField.setBackground(new java.awt.Color(204, 204, 204));
        availnumberTextField.setEnabled(false);

        priceTextField.setBackground(new java.awt.Color(204, 204, 204));
        priceTextField.setEnabled(false);

        nameTextField.setBackground(new java.awt.Color(204, 204, 204));
        nameTextField.setEnabled(false);
        nameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(descLbl1)
                            .addComponent(availnumLbl1)
                            .addComponent(priceLbl1)
                            .addComponent(nameLbl1))
                        .addGap(75, 75, 75)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nameTextField)
                            .addComponent(priceTextField)
                            .addComponent(availnumberTextField)
                            .addComponent(descriptionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(viewheadLbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(133, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(viewheadLbl1)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLbl1)
                    .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(priceLbl1)
                    .addComponent(priceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(availnumLbl1)
                    .addComponent(availnumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(descLbl1)
                    .addComponent(descriptionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(149, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void nameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTextFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel availnumLbl1;
    private javax.swing.JTextField availnumberTextField;
    private javax.swing.JLabel descLbl1;
    private javax.swing.JTextField descriptionTextField;
    private javax.swing.JLabel nameLbl1;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JLabel priceLbl1;
    private javax.swing.JTextField priceTextField;
    private javax.swing.JLabel viewheadLbl1;
    // End of variables declaration//GEN-END:variables
}
